# Treinamento e avaliação dos modelos

## Imports

In [29]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer

## Lendo conjunto de dados

In [6]:
df = pd.read_csv('../data/raw/chatbot_medical_data.csv').drop('Unnamed: 0', axis=1)
df.head(10)

,pergunta,categoria,resposta
0,como marcar consulta?,consultas,"Para marcar consultas, acesse nosso portal ou ..."
1,preciso de um dermatologista urgente,dermatologia,"Dermatologistas atendem de segunda a sexta, da..."
2,dieta personalizada,nutricao,Nossa equipe de nutrição oferece atendimento p...
3,quero marcar com especialista do coração,cardiologia,Você pode agendar uma consulta com um cardiolo...
4,emagrecer com ajuda médica,nutricao,Nossa equipe de nutrição oferece atendimento p...
5,gripe forte,gripe,"Se estiver com sintomas de gripe, procure um c..."
6,quais convênios aceitam?,convenios,Trabalhamos com diversos convênios. Consulte a...
7,quero marcar com especialista do coração,cardiologia,Você pode agendar uma consulta com um cardiolo...
8,dor no osso,ortopedia,"A ortopedia atende casos de fraturas, dores mu..."
9,aceita plano de saúde?,convenios,Trabalhamos com diversos convênios. Consulte a...

## Pré-processamento

### Funções de pré-processamento de texto

In [14]:
# Função de pré-processamento do texto
def preprocess_text(text):
    # Transformando para minúsculas
    text = text.lower()
    
    # Remover símbolos e pontuação usando expressão regular
    text = re.sub(r'[^\w\s]', '', text)
    
    # Remover espaços extras
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

### Separar dados de treinamento e labels

In [23]:
X = df.pergunta
y = df.categoria

In [24]:
X.head(10)

0                       como marcar consulta?
1        preciso de um dermatologista urgente
2                         dieta personalizada
3    quero marcar com especialista do coração
4                  emagrecer com ajuda médica
5                                 gripe forte
6                    quais convênios aceitam?
7    quero marcar com especialista do coração
8                                 dor no osso
9                      aceita plano de saúde?
Name: pergunta, dtype: object

In [25]:
y.head(10)

0       consultas
1    dermatologia
2        nutricao
3     cardiologia
4        nutricao
5           gripe
6       convenios
7     cardiologia
8       ortopedia
9       convenios
Name: categoria, dtype: object

### Pré-processando perguntas

In [28]:
X_pre = X.apply(preprocess_text)
X_pre.head(10)

0                        como marcar consulta
1        preciso de um dermatologista urgente
2                         dieta personalizada
3    quero marcar com especialista do coração
4                  emagrecer com ajuda médica
5                                 gripe forte
6                     quais convênios aceitam
7    quero marcar com especialista do coração
8                                 dor no osso
9                       aceita plano de saúde
Name: pergunta, dtype: object

### Vetorizando o conjunto de dados X_pre para usar no treinamento dos modelos TFIDF

In [34]:
# Criando o vetorizador TF-IDF
tfidf = TfidfVectorizer()

# Transformando as perguntas em vetores TF-IDF
X = tfidf.fit_transform(df['pergunta'])

# Transformando os textos em vetores TF-IDF
X_tfidf = tfidf.fit_transform(X_pre)

In [36]:
# Convertendo o X_tfidf em um pandas dataframe
df_X_tfidf = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())

df_X_tfidf.head(10)

,aceita,aceitam,agendamento,agendar,ajuda,alergia,alimentação,ansioso,aí,cabeça,...,tem,to,tosse,trabalham,tristeza,um,uma,unimed,urgente,valor
0,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.469751,0.0,0.0,0.521205,0.0
2,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
3,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
4,0.000000,0.00000,0.0,0.0,0.487264,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
5,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
6,0.000000,0.57735,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
7,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
8,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
9,0.590125,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0

### Salvando o dado vetorizado e as labels

In [38]:
df_X_tfidf.to_csv('../data/processed/perguntas_vetorized_chatbot_dataset.csv')
df.categoria.to_csv('../data/processed/labels_chatbot_dataset.csv')

### Treinamento e avaliação dos modelos